### ISSUE TITLE
fs.readFile

### ISSUE THREAD

**Issue by CraigglesO** [mafintosh/lil-pids#1]
Why are you not just using watchFile() ?

https://nodejs.org/api/fs.html#fs_fs_watch_filename_options_listener

Maybe I am missing something. I read through it fast. But this is really cool.

**Comment by mafintosh** [comment]
Cause I'm old :) PR me a fix!

**Comment by mafintosh** [comment]
Fixed it myself cause this was a cool idea

**Comment by CraigglesO** [comment]
HAHA! Ok, no worries. Yeah, sure. I'll try and make a version with watchFile.
